name: haber_noktasi
description: Haber uygulaması
publish_to: 'none' # Indicates that this package will not be published to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0 # Kesin versiyon
  cupertino_icons: ^1.0.6 # En son stabil versiyon (kontrol edildi)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # En son stabil versiyon (kontrol edildi)

flutter:
  uses-material-design: true
